### PR TITLE
updated sounds and stuff for 1.9

### PR DESCRIPTION
**Pull request by sekwah41**
Please check the player hurt should, it was HURT_FLESH before but I could not think of what it was suppose to be. These are all the updates needed for 1.9 :)

### CODE REVIEW

**Comment by Kazom** [comment]
Did this fix the extreme lag issue from 1.8?

**Comment by Steffion** [comment]
This won't fix that issue @Kazom, I can't accept this yet since the whole plugin needs to be updated. Stay tuned.

**Comment by sekwah41** [comment]
Ill need to check once the disguises are fully updated but as far as I know it seems to function in 1.9. Ill need to get some people and do a test game but as far as I know most plugins only needed the sounds changing to work how they used to in 1.8.

As I didn't write the plugin I don't know what else needs to be changed.

**Comment by TNTUP** [comment]
Hey @Steffion you're working on BlockHunt again? If so, I can't wait for it because I'm still using it and @libraryaddict fixed my issues I had with past 1.7.10/1.8.X. Now it doesn't work in 1.9, I'll keep an eye here. Mind if you can do a checklist like in ProtocolLib/LibsDisguises? That would keep us informed when you advance on features/bugs. Keep the good work, glad you're back!

**Comment by sekwah41** [comment]
I still have the code, once ProtocolLib and LibsDisguises works for 1.9 then this should work as far as I know(at the moment the only errors in the console are from LibsDisguises). If @Steffion has not released a working update when those are ready I can make a temporary fix while the official version is being fully updated.

**Comment by sekwah41** [comment]
I still have the code set up, once ProtocolLib and LibsDisguises works for 1.9 then this should work as far as I know(at the moment the only errors in the console are from LibsDisguises). If @Steffion has not released a working update when those are ready I can make a temporary fix while the official version is being fully updated.

**Comment by sekwah41** [comment]
@TNTUP I still have the code set up, once ProtocolLib and LibsDisguises works for 1.9 then this should work as far as I know(at the moment the only errors in the console are from LibsDisguises). If @Steffion has not released a working update when those are ready I can make a temporary fix while the official version is being fully updated.

**Comment by sekwah41** [comment]
Ill also take a look at the LibsDisguises and see if I can help if I have some free time. It looks like the majority of their stuff is changing the system for the new packets.

**Comment by TNTUP** [comment]
@sekwah41 Libs and Protocol works for me on my test server (dev/beta) builds but I'd wait until they get released (officially) but I'm using libraryaddict's build which fixes the severe lag issue. Latest fork of Blockhunt is updated for 1.9, but it has the severe lag issue. @Steffion If you have time, maybe port libraryaddict's fixes for the 1.9 plans? I hope for a checklist :D

**Comment by sekwah41** [comment]
I haven't tried this properly with new versions of the other plugins but this stops any of the sound errors at least http://puu.sh/nLqGk/e33bd648d6.jar If you get any errors I can possibly take a look on the weekend. Also im not sure what is causing the lag or if there is lag as I haven't properly used the plugin. Unless @Steffion is currently fixing it or the updates to the plugin are fixing this if someone can use /timings to get a report when its lagging I can take a look and see what could be causing it. Even if I don't really take a look the data could still be useful if @Steffion is not sure what is currently causing it.

**Comment by TNTUP** [comment]
@sekwah41 Take a look on libraryaddict's BlockHunt fork, he removed the nasty loop thing. Atleast this fixed this issue on my 1.8.8 server since 1.7.10. 

I don't remember what sounds are used for, but hope to see it fixed (easy fix though,  just rename sounds to the newer ones. Like BAT_TAKEOFF, missed the ENTITY_ at first). I'll give it a go and give out results

**Comment by sekwah41** [comment]
@TNTUP  the sounds I guess mostly needed to be updated to allow the plugin to run and also compile at the least.

**Comment by TNTUP** [comment]
@Steffion Sorry to comment here, do you have an ETA for the recode done? Going to switch to 1.9.2 soon (this sunday) and that's the only plugin left to update, but I'll go on 1.9.2 without it. I'll keep an eye when its ready on production servers. I remember you said signs would not work, but I haven't tried the recode yet so I can't say whats missing. Keep the good work!

**Comment by Steffion** [comment]
@TNTUP You can download the alpha version of the recode already. Have a look at the README.md file.

**Comment by Steffion** [comment]
This is fixed in the new version.
Thanks for contributing.

**Pull request closed without merging**
